name: Test Showcase

on: [pull_request]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  testShowcase:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dependencies

        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov=showcase  tests/

      - name: Test Reports
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: ./pytest.xml
          coverage-path: ./coverage.xml